# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dTjxtkw8SARWpjgJTjRq8eyzbAjLmJCf
"""

$ virtualenv venv
$ source venv/bin/activate
$ pip install flask flask-jsonpify flask-sqlalchemy flask-restful
$ pip freeze

from flask import Flask, request
from flask_restful import Resource, Api
from sqlalchemy import create_engine
from json import dumps
from flask.ext.jsonpify import jsonify

db_connect = create_engine('sqlite:///chinook.db')
app = Flask(__name__)
api = Api(app)

class Timedate(Resource):
    def get(self):
        conn = db_connect.connect() 
        query = conn.execute("select * Timedate") 
        return {'Timedate': [i[0] for i in query.cursor.fetchall()]} 

api.add_resource(Employees, '/Timedate')

if __name__ == '__main__':
     app.run(port='5002')